volumes:

  db_data:
  db_tmp:
  app_data:
  tailscale_state:

services:

  db:
    image: hbmhomelab/mariadb:${MARIADB_VERSION:-latest}
    build:
      context: ./build/mariadb/
      args:
        - backup=ccnet_db seafile_db seahub_db
        - password=${MARIADB_ROOT_PASSWORD}
        - version=${MARIADB_VERSION:-latest}
        - uid=${MARIADB_BACKUP_UID:-1000}
        - gid=${MARIADB_BACKUP_GID:-1000}
        - cron=${MARIADB_BACKUP_CRON_SCHEDULE:-15 0 * * *}
        - keep=${MARIADB_BACKUP_KEEP:-7}
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - db_data:/var/lib/mysql
      - db_tmp:/tmp
      - ./backup:/backup
      - /sys/fs/cgroup/memory.pressure:/sys/fs/cgroup/memory.pressure
    labels:
      - deunhealth.restart.on.unhealthy=true
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      tailscale:
        condition: service_healthy

  memcached:
    image: memcached:1.6.18
    entrypoint: memcached -m 256
    restart: on-failure
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      tailscale:
        condition: service_healthy

  app:
    image: seafileltd/seafile-mc:11.0-latest
    network_mode: service:tailscale
    restart: on-failure
    environment:
      - DB_HOST=db
      - FORCE_HTTPS_IN_CONF=true
      - SEAFILE_SERVER_LETSENCRYPT=false
      - TIME_ZONE=${TZ}
      - DB_ROOT_PASSWD=${MARIADB_ROOT_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=${TAILSCALE_HOSTNAME}.${TAILSCALE_TAILNET}.ts.net
      - SITE_TITLE=${SEAFILE_SITE_TITLE}
      - EMAIL_HOST=${SEAFILE_EMAIL_HOST}
      - EMAIL_PORT=${SEAFILE_EMAIL_PORT}
      - EMAIL_USE_TLS=${SEAFILE_EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${SEAFILE_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${SEAFILE_EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${SEAFILE_DEFAULT_FROM_EMAIL}
    volumes:
      - app_data:/shared
      - ./config/seafile:/shared/seafile/conf
      - ./storage:/shared/seafile/seafile-data/storage
    labels:
      - deunhealth.restart.on.unhealthy=true
    depends_on:
      memcached:
        condition: service_started
      db:
        condition: service_healthy
        restart: true
      tailscale:
        condition: service_healthy
        restart: true

  pbs-client:
    image: aterfax/pbs-client
    restart: on-failure
    network_mode: service:tailscale
    environment:
      - TZ=${TZ}
      - PBS_ENDPOINT=${PBS_ENDPOINT}
      - PBS_DATASTORE=${PBS_DATASTORE}
      - PBS_API_KEY_NAME=${PBS_API_KEY_NAME}
      - PBS_API_KEY_SECRET=${PBS_API_KEY_SECRET}
      - PBS_ENCRYPTION_PASSWORD=${PBS_ENCRYPTION_PASSWORD}
      - CRON_SCHEDULE=${PBS_CRON_SCHEDULE:15 1 * * *}
    volumes:
      - ./config/pbs-client:/root/.config/proxmox-backup/
      - ./backup:/backups/db:ro
      - ./storage:/backups/storage:ro
    tmpfs:
      - /tmp
      - /run:exec

  tailscale:
    image: tailscale/tailscale:latest
    hostname: $TAILSCALE_HOSTNAME
    restart: on-failure
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_TAILSCALED_EXTRA_ARGS=--no-logs-no-support
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/ts-serve.json
      - TS_ENABLE_HEALTH_CHECK=true
    volumes:
      - tailscale_state:/var/lib/tailscale
      - ./ts-serve.json:/config/ts-serve.json
    labels:
      - deunhealth.restart.on.unhealthy=true
    healthcheck:
      test: wget -q --tries=1 --spider http://127.0.0.1:9002/healthz || exit 1
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
