services:
  mysql:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
        restart: true

  memcached:
    image: memcached:1.6.18
    entrypoint: memcached -m 256
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
        restart: true

  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    volumes:
      - /opt/seafile-data:/shared
    environment:
      - NON_ROOT=true
      - DB_HOST=seafile-mysql
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWD}
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - FORCE_HTTPS_IN_CONF=true
      - SEAFILE_SERVER_HOSTNAME=${TAILSCALE_HOSTNAME}.${TAILSCALE_TAILNET}.ts.net
    depends_on:
      db:
        condition: service_started
      memcached:
        condition: service_started
      tailscale:
        condition: service_healthy
        restart: true
    network_mode: service:tailscale

  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${TAILSCALE_HOSTNAME}
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_TAILSCALED_EXTRA_ARGS=--no-logs-no-support
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/ts-serve.json
      - TS_ENABLE_HEALTH_CHECK=true
    volumes:
      - tailscale_state:/var/lib/tailscale
      - ./ts-serve.json:/config/ts-serve.json
    networks:
      default:
        aliases:
          - seafile-memcached
          - seafile-mysql
    healthcheck:
      test: wget -q --tries=1 --spider http://127.0.0.1:9002/healthz || exit 1
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: on-failure

  deunhealth:
    image: qmcgaw/deunhealth
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none
    restart: always

volumes:
  tailscale_state:
